  discord-bot:
    build: .
    container_name: glances_discord_bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=ここに_BOT_TOKEN_を貼り付け
      - GLANCES_API_URL=http://localhost:61208/api/4 
    network_mode: host